default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 4r2w3e1q
  hostname: localhost
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: test2_development

test:
  <<: *default
  database: test2_test

production:
  <<: *default
  database: test2_production
